### ISSUE TITLE
My bugs v1. 0.5

### ISSUE THREAD

**Issue by xdk78** [k0shk0sh/FastHub#60] opened 2017-03-05 06:46 UTC
__user profile(in navigation) __ 
You should remove follow button - because I don't want follow myself :) 
__repo__
Branches doesn't working properly, only refreshing files, without commits 
__everywhere __
Still incorrect timestamp. 

Thanks, for your hard work :)

**Comment by k0shk0sh** [comment] 2017-03-05 06:54
damn, I thought i fixed the time 😞. will see if i can make it today. for branches, each branch has its file listing,what ever you seeing when you select a branch is what the branch has. 
there are still more room for improvement.

**Comment by xdk78** [comment] 2017-03-05 07:00
Ok, thanks

**Comment by xdk78** [comment] 2017-03-05 07:14
One more thing : can you remove one of loading circles from main screen?
Swipe to refresh is enough IMO.

**Comment by kutsan** [comment] 2017-03-05 07:17
@xdk78 I also agree. He should remove one of them.

**Comment by k0shk0sh** [comment] 2017-03-05 07:18
only progressBar will be showing at a time in 1.0.5 unless if you swipe to refeesh. then both will appear. could you guys confirm you are on 1.0.5?

**Comment by xdk78** [comment] 2017-03-05 07:22
Yes, [Imgur](http://i.imgur.com/TnTXstF.jpg)

**Comment by k0shk0sh** [comment] 2017-03-05 07:24
@xdk78 cool, can you confirm on what i said above?

**Comment by kutsan** [comment] 2017-03-05 07:30
I am on 1.0.5. And I can confirm double loading bar only shows when swipe to refresh.

**Comment by xdk78** [comment] 2017-03-05 07:31
So, as you can see http://imgur.com/jYyfxJl two loading circles.

**Comment by k0shk0sh** [comment] 2017-03-05 07:33
@xdk78 as I mentioned two will appear if you pull to refresh. is this is the scenario you having?

**Comment by xdk78** [comment] 2017-03-05 07:33
Yes

**Comment by kutsan** [comment] 2017-03-05 07:44
@k0shk0sh Also, a quick question. I have updated from 1.0.4 to 1.0.5 and I saw you have added a few new features and bump the patch release version. Why? You should stick with [semver.org](semver.org).

**Comment by k0shk0sh** [comment] 2017-03-05 07:52
@kutsan I did that because these features were supposed to be from 1.0.0 and didn't think that fashub is amateur enough to jump to 1.1.0 yet

**Comment by kutsan** [comment] 2017-03-05 12:56
@k0shk0sh But this is not version systems work. If you want this in standard way you should obey Semantic Versioning. Also, you don't need to bump the version every few features if you think minor release not ready. I just say.

**Comment by k0shk0sh** [comment] 2017-03-05 12:59
@kutsan thanks kutsan, I'll keep this in mind when releasing next time.

**Comment by k0shk0sh** [comment] 2017-03-06 03:51
Time  now should work fine in 1.0.6 i rushed this release due to serious bug in PR. next release will only be available weekends. thanks for your patience.

**Comment by k0shk0sh** [comment] 2017-03-08 12:58
I guess I'll be closing this issue as all of the issues mentioned above are fixed except for the progressbar which is going to stay for awhile :p

**Closed by k0shk0sh** 2017-03-08 12:58 UTC
Labels: enhancement, High Priority
