### ISSUE TITLE
Can't upload images

### ISSUE THREAD

**Issue by OffifialMITX** [k0shk0sh/FastHub#480] opened 2017-05-14 12:13 UTC
**App Version: 2.1.0**

**OS Version: 22**

**Model: TP-LINK-TP601A**

Every time I try to, I get the error message "Failed to communicate to server"

**Comment by JediBurrell** [comment] 2017-05-14 12:16
Are you on release or commit?

**Comment by k0shk0sh** [comment] 2017-05-14 12:19
![](http://i.imgur.com/h9KXAWN.png)


_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment] 2017-05-14 12:19
@JediBurrell got the same thing now looks like github went down for a few min

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment] 2017-05-14 12:20
@yakov116 just uploaded one 😕

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment] 2017-05-14 12:24
@OffifialMITX Oh wait:

>"Failed to communicate to server"

Try to leave the area you're commenting on completely back to the home page, re-open the repo / gist you're trying to comment on, and try again. This may be a different issue.

**Comment by yakov116** [comment] 2017-05-14 12:28
@k0shk0sh for me too

I said that it went down for a few min.

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment] 2017-05-14 12:29
@JediBurrell yes I know. Many times I have to go out and back in. 

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment] 2017-05-14 13:19
After some testing, this is an issue with missing keys.
If you are running on a custom build / latest commit, you will need to generate custom Imgur keys.
Otherwise, you'll need to revert to the latest release.

The keys are non public information, and are only added on signed builds officially released.

I'll be closing this, thank you for your report.

**Closed** 2017-05-14 13:19 UTC
Labels: Status: Needs More Information

**Comment by OffifialMITX** [comment] 2017-05-16 18:37
So, as a person who uses the latest build from F-Droid with almost no understanding of what you said, what can I do?

**Comment by jancborchardt** [comment] 2017-11-10 18:42
Yeah, same confusion here. What do people using the release from F-Droid need to do?

**Comment by yakov116** [comment] 2017-11-10 18:44
@jancborchardt get the real release!

**Comment by jancborchardt** [comment] 2017-11-10 18:48
@yakov116 no need for an exclamation mark after a non-helpful comment. I'm aware it will work in the "real" release, however much like @OffifialMITX I was wondering if there's a way to do it with the F-Droid version.

**Comment by yakov116** [comment] 2017-11-10 18:50
@jancborchardt There is no change to my knowledge. They are using the same imgur api with their own key. I dont see what exactly the issue is.

**Comment by k0shk0sh** [comment] 2017-11-10 18:51
@jancborchardt could you calm down? I don't care much about fdroid so your bet to head to the fork of this repo where they maintain their own fork. 

So if you are using fdroid and having problems, you should report there and here.

**Comment by jancborchardt** [comment] 2017-11-11 00:07
@k0shk0sh I am calm, not sure how my comments indicated otherwise.

Thanks for pointing out there's a fork, that's very helpful. Wasn't aware that the F-Droid release is done by another person. Thanks :)
