### ISSUE TITLE
Logged in user's profile pictures don't update

### ISSUE THREAD

**Issue by peaches6** [k0shk0sh/FastHub#1413] opened 2018-01-13 13:36 UTC
I'm not sure if this is on all devices, but the current logged in user's profile picture doesn't update when changed, requires a clear of application data/cache to refresh it. When clicked on, it (obviously) loads the new one however.

**FastHub Version:**  4.6.1
**Android Version:**  8.0
- MANUFACTURER:  OnePlus
- BRAND: OnePlus
- MODEL: 3

**Comment by dedepete** [comment] 2018-01-13 13:45
Seems to be a duplicate of #1385. Restarting the app should help.

**Closed** 2018-01-13 13:46 UTC
Labels: Type: Duplicate

**Comment by peaches6** [comment] 2018-01-13 19:17
Restarting the app or phone does not help, as mentioned, application cache must be cleared

**Comment by peaches6** [comment] 2018-01-13 19:17
Restarting the app or phone does not help, as mentioned, application cache must be cleared

**Comment by peaches6** [comment] 2018-01-13 19:17
Restarting the app or phone does not help, as mentioned, application cache must be cleared

**Comment by peaches6** [comment] 2018-01-13 19:17
Restarting the app or phone does not help, as mentioned, application cache must be cleared

**Comment by yakov116** [comment] 2018-01-14 00:57
@peaches6 disagree did you try to force stop the app?

**Comment by peaches6** [comment] 2018-01-14 01:15
Yup, and I'm still on my profile picture 3 changes ago
