### ISSUE TITLE
PR checks that passed are marked as failed

### ISSUE THREAD

**Issue by maxbycode** [k0shk0sh/FastHub#654] opened 2017-06-14 04:57 UTC
---

![image](https://user-images.githubusercontent.com/11779550/27115963-6474fdf0-508b-11e7-8edd-cbd3f38a7193.png)

This PR says that all checks have failed but on the GitHub website it says they had passed:

![image](https://user-images.githubusercontent.com/11779550/27115984-7f939aba-508b-11e7-95b4-d7ada4231c98.png)

However, the check messages say the checks have passed within them as well.

 - FastHub Version: 3.1.0
 - Android Version: Android O DP3
 - Phone Model: Google Pixel

**Comment by k0shk0sh** [comment] 2017-06-14 05:07
Hey, thanks for reporting,
Could you give me the PR link? 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by maxbycode** [comment] 2017-06-14 06:06
[Here you go](https://github.com/v0lture/v0.lt/pull/11)!

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment] 2017-06-14 20:57
Discovered another 2 bugs and 1 enhancement when testing this issue.

1.  The merged is doubled and has the wrong wording.
  1a.  Its missing the branch it was merged into
  1b. Should say `merged commit` `<commit number>`  `into` `<branch name>`
2. The referencing is not correct.
    2a. Its missing where is was referenced
    2b. When clicking on it, it just loads a blank page.
3. The __[bot]__ should be displayed as `[bot]`

**Comment by maxbycode** [comment] 2017-06-15 00:55
Also to add on, the details count towards the top tabs says 0 when there is obviously more than 0 details in the PR.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment] 2017-06-15 00:57
@maxbycode the count is meant for comments not for the overall details. I haven't yet to check on this issue as I wasn't free yesterday, I'm sure GitHub saying that something didn't pass I'll post my finding as soon as I get my hand on it.

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by maxbycode** [comment] 2017-06-15 01:23
@k0shk0sh ah fair enough. Thanks for looking into it though!

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment] 2017-06-15 05:38
@k0shk0sh when looking this issue I discovered another one.
The 1 1a 1b are not intended correctly 

![](http://i.imgur.com/5e7oChT.png)


_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment] 2017-06-15 13:29
well it appears to be looking fine, looking at the PR link you gave me, there are 2 checks and one of them failed, looking as well at github api, it clearly says the status is failure 

https://api.github.com/repos/v0lture/v0.lt/commits/dafe473de58d1ec38cd31e14dea9ad26a017674f/status

**Closed by k0shk0sh** 2017-06-15 13:29 UTC
Labels: Priority: High, Status: Accepted, Type: Investigate

**Comment by k0shk0sh** [comment] 2017-06-15 13:34
but, hey that PR actually made me realize that there is one more status that should be showing & i'm not even catching it, which is `error` currently, only, failure, success & pending I was handling them, this will be showing in next release, thank you very much :)

**Comment by k0shk0sh** [comment] 2017-06-15 13:36
![](http://i.imgur.com/6vOwTm1.png)


_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment] 2017-06-15 13:45
@k0shk0sh I should make a new ticket with the other things? Or you have them?

**Comment by k0shk0sh** [comment] 2017-06-15 13:54
make new one in your issues list.

**Comment by yakov116** [comment] 2017-06-15 15:52
@k0shk0sh the issue is that the commit failed but when it was merged it passed.

I guess when you add support for cli on a commit we will come back to this

**Comment by maxbycode** [comment] 2017-06-15 16:07
Cool. I guess I didn't see the other check then when looking. Thanks for fixing the one that didn't show though!

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
