### ISSUE TITLE
Fc! While scrolling the Repository column.

### ISSUE THREAD

**Issue by Genxster1998** [k0shk0sh/FastHub#600] opened 2017-06-03 16:19 UTC
**App Version: 2.5.3**

**OS Version: 25**

**Model: Xiaomi-Redmi Note 3**

 Searched the keyword "Android mac"

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment] 2017-06-03 16:55
Couldn't really reproduce it , went to search, keyed Android mac, scrolled almost ten pages nothing happened, which mean it's fixed with the bug I triggered due to the repo language was null. 
Thanks for reporting it'll be in later release

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Closed by k0shk0sh** 2017-06-03 16:55 UTC
