### ISSUE TITLE
Disable line-wrapping in diffs

### ISSUE THREAD

**Issue by jonsmithers** [k0shk0sh/FastHub#981] opened 2017-09-16 16:05 UTC
**FastHub Version:**  4.2.0 
**Android Version:**  8.0.0
**Device Information:**  
- MANUFACTURER: Huawei   
- BRAND: Nexus   
- MODEL: Nexus 6P 
---

I haven't seen any option to disable line-wrapping for diffs of commits or pull requests. I like that you can disable line wrapping when viewing code. I think it would be nice to also disable it when viewing diffs of code. It would make things easier to read.

![screenshot_20170916-115036](https://user-images.githubusercontent.com/2660313/30513696-ced19b9c-9ad5-11e7-90d8-edccef5527ea.png)

**Comment by k0shk0sh** [comment] 2017-09-16 16:06
this isn't possible as I'm using text view and not webview, but isn't wrapping the code will make it look different from how it really looks like?

**Comment by jonsmithers** [comment] 2017-09-16 16:17
I'm not sure I know what you mean, but I see know down sides to not wrapping it.

I have to say I'm not at all familiar with Android development, but...is this relevant? https://developer.android.com/reference/android/widget/TextView.html#attr_android:scrollHorizontally

**Comment by k0shk0sh** [comment] 2017-09-16 16:19
owh, I just got what you mean, the text is out of the boundaries 😰😰😰😰. will be fixed in tomorrow release, on it right now.

could you please pass me the link to that commit that contains the screenshot you posted here.

**Comment by jonsmithers** [comment] 2017-09-16 16:32
This would be general behavior for all diffs. It's not really a special case. But that commit can be found [here](https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/commit/a047be85247755cdbe0acce6f1dafc8beb84f2ac)

**Comment by k0shk0sh** [comment] 2017-09-16 18:08
![](https://i.imgur.com/oqVHq1f.png)

can't produce it

**Comment by k0shk0sh** [comment] 2017-09-16 18:25
I couldn't reproduce it, but i did enable the horizontal scrolling, lets see how it will in tomorrow's release :)

**Closed by k0shk0sh** 2017-09-16 18:25 UTC
Labels: Status: Completed
