### ISSUE TITLE
Back button does not return to app when fasthub is opened as url handler for github

### ISSUE THREAD

**Issue by ibrokemypie** [k0shk0sh/FastHub#581] opened 2017-05-29 15:34 UTC
**App Version: 2.5.3**

**OS Version: 25**

**Model: HTC-HTC 10**

 eg in chrome, after tapping a github link and having it open in fasthub, pressing back then goes to whatever you were last doing in fasthub, rather than returning to chrome

**Comment by yakov116** [comment] 2017-05-29 15:37
Duplicate of #568

**Closed by yakov116** 2017-05-29 15:37 UTC
Labels: Type: Duplicate

**Comment by k0shk0sh** [comment] 2017-05-29 16:58
It's fixed and soon will be released

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
