### ISSUE TITLE
Unable to close update notification

### ISSUE THREAD

**Issue by VictorGaiva** [k0shk0sh/FastHub#1481] opened 2018-02-02 12:11 UTC
**FastHub Version: 4.6.2**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G3  
---

1- Opened app
2- Got notified about update
3- Closed pop up
4- Opened a notification
5- Popup appeared again but clicking on 'X' has no effect. Pressed "Back" button and the popup wouldn't close and app would do nothing.
6- Closed the app and opened again and issue was gone.

**Comment by dedepete** [comment] 2018-02-02 12:27
Duplicate of #1440.

**Closed by dedepete** 2018-02-02 12:27 UTC
Labels: Type: Duplicate
