### ISSUE TITLE
Query URL encoding is incorrect

### ISSUE THREAD

**Issue by JortvD** [k0shk0sh/FastHub#1461] opened 2018-01-28 11:12 UTC
**FastHub Version:**  4.6.2
**Android Version:**  7.0 (SDK: 24)
**Device Information:**  
- MANUFACTURER: Huawei 
- BRAND: Huawei
- MODEL: P9 Lite
---

By default, GitHub encodes all the non-unreserved characters that are used in a query. These unreserved characters that shouldn't be encoded are: ALPHA, DIGIT, "-", ".", "_" and "~" (as specified in RFC 3986). The remaining characters **should** be encoded. 

**An example:**
When searching for repositories with c++ as language ("name language:c++") only c repositories are returned. This happens since the + is directly used in the query which GitHub validates as invalid and thereby doesn't use.

**Notes:**
It should be noted that unsafe characters: "{", "}", "|", "\", "^", "~", "[", "]", and "`" (as specified in RFC 1738) aren't used in a query if they are encoded or not.

**Comment by dedepete** [comment] 2018-01-28 13:05
Seems to be a duplicate of #1438

**Comment by JortHub** [comment] 2018-01-28 13:41
My bad, I missed that issue while writing this issue. Having said that, #1438 is still incomplete since the url encoding used for requests to the api is probably incorrect for the whole app.

**Closed** 2018-06-17 16:15 UTC
Labels: Type: Duplicate
