### ISSUE TITLE
Reaction buttons incorrectly increasing counts

### ISSUE THREAD

**Issue by nyuszika7h** [k0shk0sh/FastHub#524] opened 2017-05-23 17:26 UTC
**App Version: 2.1.0**

**OS Version: 25**

**Model: LGE-Nexus 5X**

 This is a follow-up to #232, as I was told to open another issue.

It seems when you tap on a reaction button, the app always just increments the count by one, and the correct counts are only displayed if you press the back button and open the issue again (reloading doesn't seem to be enough).

Due to GitHub API limitations, this should probably be implemented by re-requesting the reaction counts from after sending the user's reaction, and disabling the reaction buttons and showing some sort of indicator while the request is being processed.

If the user already reacted to an issue in the current session (for simplicity's sake, a session could be as short as until you leave the issue page or exit the app, whichever comes first), then a local prediction can be made, though it may be best to always re-request the reaction counts to make sure.

**Comment by cozyplanes** [comment] 2017-10-03 06:36
(quietly) isn't this fixed?

**Comment by cozyplanes** [comment] 2017-12-24 03:02
@k0shk0sh hello? That milestone seems to be a history

**Comment by Djfe** [comment] 2018-11-29 12:32
just discovered this

not only can't I react to posts with the same reaction, I can't add any reaction to posts at all. they aren't send correctly to the github server.
reloading the issue is enough and they are gone

**Comment by yakov116** [comment] 2018-11-29 14:30
@Djfe 	it will be fixed in version 5

**Comment by yakov116** [comment] 2019-12-29 03:31
This has been fixed in v4

**Closed by yakov116** 2019-12-29 03:31 UTC
Labels: Priority: Critical, Status: Accepted, Type: Enhancement
