### ISSUE TITLE
[Issue] Wiki Pages Blank

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [k0shk0sh/FastHub#2463] opened 2019-05-18 12:58 UTC
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** V40 ThinQ  
---

 So basically, I find more often than not a lot of the Wiki pages are completely blank, where in return when opened in the browser they show.

**Comment by ridespirals** [comment] 2019-05-18 17:09
See #1972

**Comment by yakov116** [comment] 2019-05-19 03:06
duplicate of #1972

**Closed by yakov116** 2019-05-19 03:06 UTC
