### ISSUE TITLE
Rendering ipython notebooks

### ISSUE THREAD

**Issue by Dreamersoul** [k0shk0sh/FastHub#1616] opened 2018-03-14 06:39 UTC
**FastHub Version: 4.6.4**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

 I think that rendering ipython notebooks would be an amazing feature and can be done using the following Javascript library embedding it in a webview
[Nbpreview](https://github.com/jsvine/nbpreview)

It's just a suggestion and I think it can be done using native Android components while maintaining the theme

**Comment by dedepete** [comment] 2018-03-14 06:48
Duplicate of #1069 .

_Отправлено с моего P2 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Closed** 2018-03-14 06:48 UTC
Labels: Status: Won't Implement, Type: Duplicate
