### ISSUE TITLE
Epilepsy when selecting a release with a body.

### ISSUE THREAD

**Issue by bored-person** [k0shk0sh/FastHub#2377] opened 2019-04-08 06:37 UTC
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note9  
---

 So if you select a realese/tag. It would constantly snap up and down very fast. This causes a epilepsy-type effect and its weird to be honest. Please tell me if you want anymore details. I'll try to make a video later.

**Comment by yakov116** [comment] 2019-04-08 12:33
Duplicate of #2281

**Closed by yakov116** 2019-04-08 12:33 UTC
