### ISSUE TITLE
Stale notification content

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#258] opened 2017-04-05 05:37 UTC
If an issue I am watching has an action taken on it (closed, re-opened, etc...), I get a notification, but the notification's content contains the first comment on the issue.

**Comment by k0shk0sh** [comment] 2017-04-05 05:53
I don't think that this is doable as you can see from this json below, there is no way I could tell if the issue is being closed or opened.
So this will be marked as wontfix.  

```
{
  "items": [
    {
      "id": "214900190",
      "unread": true,
      "reason": "author",
      "updated_at": "2017-04-05T05:47:39Z",
      "last_read_at": null,
      "subject": {
        "title": "testing close issue notification.",
        "url": "https://api.github.com/repos/FastAccess/testing_pullrequest/issues/3",
        "latest_comment_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/issues/3",
        "type": "Issue"
      },
      "repository": {
        "id": 83865026,
        "name": "testing_pullrequest",
        "full_name": "FastAccess/testing_pullrequest",
        "owner": {
          "login": "FastAccess",
          "id": 26117412,
          "avatar_url": "https://avatars1.githubusercontent.com/u/26117412?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/FastAccess",
          "html_url": "https://github.com/FastAccess",
          "followers_url": "https://api.github.com/users/FastAccess/followers",
          "following_url": "https://api.github.com/users/FastAccess/following{/other_user}",
          "gists_url": "https://api.github.com/users/FastAccess/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/FastAccess/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/FastAccess/subscriptions",
          "organizations_url": "https://api.github.com/users/FastAccess/orgs",
          "repos_url": "https://api.github.com/users/FastAccess/repos",
          "events_url": "https://api.github.com/users/FastAccess/events{/privacy}",
          "received_events_url": "https://api.github.com/users/FastAccess/received_events",
          "type": "User",
          "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/FastAccess/testing_pullrequest",
        "description": "testing pr",
        "fork": false,
        "url": "https://api.github.com/repos/FastAccess/testing_pullrequest",
        "forks_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/forks",
        "keys_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/teams",
        "hooks_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/hooks",
        "issue_events_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/issues/events{/number}",
        "events_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/events",
        "assignees_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/assignees{/user}",
        "branches_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/branches{/branch}",
        "tags_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/tags",
        "blobs_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/languages",
        "stargazers_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/stargazers",
        "contributors_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/contributors",
        "subscribers_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/subscribers",
        "subscription_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/subscription",
        "commits_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/contents/{+path}",
        "compare_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/merges",
        "archive_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/downloads",
        "issues_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/issues{/number}",
        "pulls_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/labels{/name}",
        "releases_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/releases{/id}",
        "deployments_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/deployments"
      },
      "url": "https://api.github.com/notifications/threads/214900190",
      "subscription_url": "https://api.github.com/notifications/threads/214900190/subscription"
    }
  ]
}
```

**Closed by k0shk0sh** 2017-04-05 05:53 UTC

**Comment by eygraber** [comment] 2017-04-05 05:57
@k0shk0sh if I look in the GitHub notifications on the website, it looks me to [something like this](https://github.com/k0shk0sh/FastHub/issues/257#event-1029719347). 

Is that accessible from anywhere, or do they use a different API?

**Comment by k0shk0sh** [comment] 2017-04-05 06:01
If you mean anchor links, then yes, its passed along with `html_url` something like 
```{html_url: https://github.com/k0shk0sh/FastHub/issues/258#issuecomment-291761501}```

**Comment by eygraber** [comment] 2017-04-05 06:05
Can that be used to parse the action?

**Comment by k0shk0sh** [comment] 2017-04-05 06:11
Looking at [this](https://developer.github.com/v3/activity/notifications/#notification-reasons), there is actually something called state_changed however isn't passed within the API, and I can't use that because as you can see from the json i posted previously, it doesn't have that URL. 

```
"id": "214900190",
      "unread": true,
      "reason": "author",
      "updated_at": "2017-04-05T06:09:20Z",
      "last_read_at": "2017-04-05T06:03:36Z",
      "subject": {
        "title": "testing close issue notification.",
        "url": "https://api.github.com/repos/FastAccess/testing_pullrequest/issues/3",
        "latest_comment_url": "https://api.github.com/repos/FastAccess/testing_pullrequest/issues/3",
        "type": "Issue"
      }
```

**Comment by k0shk0sh** [comment] 2017-04-05 06:15
![Uploading Screen Shot 2017-04-05 at 2.15.03 PM.png…](Image) Even in their notification panel they can't determine that :D
