### ISSUE TITLE
Tool crashes when PR is opened

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#739] opened 2017-07-07 10:22 UTC
Open [this PR](https://github.com/AutoFixture/AutoFixture/pull/773) and try to scroll down to the bottom. In my case application crashes somewhere in the middle of the PR :(

-------

**App Version: 3.2.0**

**OS Version: 24**

**Model: Xiaomi-MI 5**

**Comment by k0shk0sh** [comment] 2017-07-07 10:26
Yeep, crashes I'll look into it once I'm on my laptop. Thanks.

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zvirja** [comment] 2017-07-07 10:26
I've submitted you the Android report and added issue ID to description.

**Comment by k0shk0sh** [comment] 2017-07-07 10:27
@zvirja thanks alot & sorry for the inconvenience. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zvirja** [comment] 2017-07-07 10:36
No problem, thanks for looking into this :wink:

**Comment by k0shk0sh** [comment] 2017-07-08 05:54
Alright, got what is the cause, `requested_team` which I didn't handle this & always thought that its `requested_reviewer` :'(  ... its fixed and will be released tomorrow hopefully.

**Closed** 2017-07-08 06:42 UTC
Labels: Priority: Critical, Status: Completed, Type: Bug
