### ISSUE TITLE
Improve design in label section

### ISSUE THREAD

**Issue by dikiaap** [k0shk0sh/FastHub#286] opened 2017-04-10 16:29 UTC
I had an issue, the font in label is not going well and out of the background.

Portrait mode:
![tmp_3470-screenshot_2017-04-10-23-13-43 01-2125737646](https://cloud.githubusercontent.com/assets/8542502/24871599/521810ee-1e44-11e7-8ee3-7dae13142bec.png)

Landscape mode:
![tmp_5007-screenshot_2017-04-10-23-34-18 01-1840010999](https://cloud.githubusercontent.com/assets/8542502/24872206/d395e87e-1e46-11e7-81cc-51de936cb50e.png)

 - FastHub Version: 1.8.1
 - Android Version: 5.1
 - Phone Model: Android One

**Comment by arkon** [comment] 2017-04-19 14:31
I'm still seeing issues with the labels.

![2017-04-19 14 02 53](https://cloud.githubusercontent.com/assets/4098258/25185438/55c19e1a-24eb-11e7-99f6-601d026aeb62.png)

**Comment by kutsan** [comment] 2017-04-19 16:00
Can confirm. I am also having this issue.

**Comment by k0shk0sh** [comment] 2017-04-19 16:08
If you guys have custom density then maybe that's the cause. I'll look at when I'm free, meantime good night
![](http://i.imgur.com/ENvYtwm.png)
![](http://i.imgur.com/0dUSNUH.png)

**Comment by arkon** [comment] 2017-04-19 16:10
That's what I thought too, but it still looks the same after switching back to the normal density.

**Comment by kutsan** [comment] 2017-04-19 16:10
@k0shk0sh Nope, I didn't set custom destiny. Good night!

**Comment by k0shk0sh** [comment] 2017-04-23 09:47
This should be fixed in 1.9.4, please update from  playstore.

**Comment by dikiaap** [comment] 2017-04-23 17:26
Now some labels are bigger
![screenshot_2017-04-24-00-21-46](https://cloud.githubusercontent.com/assets/8542502/25315747/6c0b52be-2884-11e7-87ff-f534d2ed72c0.png)

But this one looks normal
![screenshot_2017-04-24-00-22-28](https://cloud.githubusercontent.com/assets/8542502/25315753/906a3ec2-2884-11e7-86b8-37c13ce73336.png)

**Comment by kutsan** [comment] 2017-04-23 17:29
Again, can confirm. Some of them are bigger than others.

**Comment by k0shk0sh** [comment] 2017-04-23 17:33
@kutsan what's wrong with this? I mean base on text length definitely they will look bigger?

**Comment by k0shk0sh** [comment] 2017-04-23 17:37
Owwh, you mean, those single & multiple levels are different, will yes they are

**Comment by arkon** [comment] 2017-04-23 17:39
I'm seeing this too. The contrast levels are generally too low as well.

**Comment by kutsan** [comment] 2017-04-23 17:41
@k0shk0sh Like [this](https://i.imgur.com/DHop0V7.png) and [this](https://i.imgur.com/B27uZTa.png).

And seems like you should reopen the issue again. :D

**Comment by k0shk0sh** [comment] 2017-04-23 18:04
It was intentional imho, since I had to do extra job for the sake of combining multiple labels in one, so I had to draw extra spacing between labels (Drawing is done here in a single `TextView`) and left the single label as it is but modified it abit, larger == more space, smaller == no space. my next update will be final lol. as tbh, this issue is causing me loads of headache :D

**Comment by kutsan** [comment] 2017-04-23 18:07
Can't even imagine. Looks like a bug though.

[#itsafeature](https://geekwhisperin.files.wordpress.com/2009/09/bug-vs-feature.jpg)

**Comment by k0shk0sh** [comment] 2017-04-23 18:08
@kutsan multiple labels == you. lool :D

**Comment by kutsan** [comment] 2017-04-23 18:09
lol :D

**Comment by k0shk0sh** [comment] 2017-04-23 18:27
Please tell me you guys happy,
@arkon how about text color now? 

![](http://i.imgur.com/cVTxGJr.png)

**Comment by kutsan** [comment] 2017-04-23 18:28
@k0shk0sh I think much better.

**Comment by k0shk0sh** [comment] 2017-04-23 18:29
@kutsan thank god. Lol

**Closed** 2017-04-23 18:31 UTC
Labels: Priority: Medium, Status: In Progress, Type: Enhancement

**Comment by arkon** [comment] 2017-04-23 18:52
LGTM 👍
