### ISSUE TITLE
Code feed not working

### ISSUE THREAD

**Issue by ravi962941** [k0shk0sh/FastHub#1010] opened 2017-09-26 02:13 UTC
**FastHub Version: 4.3.0**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi Note 3  
---

Hi when I search something in the code feed it shows the no of results at top but it is showing no results at the bottom

**Comment by yakov116** [comment] 2017-09-26 02:42
@ravi962941 please search before opening an issue. 

Duplicate of #1006 and others 

Thanks for your feedback

**Closed** 2017-09-26 02:42 UTC
