### ISSUE TITLE
Can't edit my own issues from FastHub

### ISSUE THREAD

**Issue by Younes-L** [k0shk0sh/FastHub#952] opened 2017-09-10 16:32 UTC
**FastHub Version: 4.2.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** oneplus  
- **Model:** OnePlus One  
---

When I try to submit an issue edit, it says "not editable by <me>"

Works fine from github web desktop on chrome android.
This happened on 4.1.0 as well...

**Comment by k0shk0sh** [comment] 2017-09-10 16:34
I can't produce that, its GitHub message that is displayed so I'm unsure why GitHub doesn't like that.

**Comment by Younes-L** [comment] 2017-09-10 16:37
@k0shk0sh it works on this report but not on the lawnchair repo... do you think it needs FastHub access or something ?

**Comment by k0shk0sh** [comment] 2017-09-10 16:41
I'm not so sure about that honestly. it's weird.

**Comment by Younes-L** [comment] 2017-09-10 16:43
![Screen recording](https://photos.app.goo.gl/7sNb14E4imTqMdZ32)

**Comment by k0shk0sh** [comment] 2017-09-10 16:58
That's a response from GitHub @zvirja is having the same issue yesterday, i'm not really sure honestly, but maybe something has to do with settings in repo?
![screen shot 2017-09-10 at 6 56 44 pm](https://user-images.githubusercontent.com/960767/30251115-fc9a86fe-9659-11e7-93e2-197bbdfa53b3.png)

I'm 100% sure that it isn't FastHub issue 😕

**Comment by yakov116** [comment] 2017-09-10 17:00
@k0shk0sh Why dont we try it?

**Comment by k0shk0sh** [comment] 2017-09-10 17:01
@yakov116 I have tried editing an issue once this issue is opened #384

**Comment by k0shk0sh** [comment] 2017-09-10 17:02
@yakov116 I have go to your private repo and edited an issue and it was success 😖

**Comment by zvirja** [comment] 2017-09-10 17:02
[I'm still having](https://github.com/k0shk0sh/FastHub/issues/948) this issue today with issues from _this_ repo. I've tried on different devices but everything situation is the same.

Given that issue is very popular, either something changed in app (should test with previous version) or within GitHub.

**Comment by yakov116** [comment] 2017-09-10 17:04
@k0shk0sh Should i make a debug of 4.30?

**Comment by k0shk0sh** [comment] 2017-09-10 17:05
@zvirja nothing has changed at all for editing issue. and when I marked the issue with can't produce meaning that I have tried it & couldn't produce the issue. 
With that said, maybe I suggest you guys to contact GitHub or if anyone of you right now is available, join FastHub slack from readme, DM me and i'll send you an apk that copies the response. 

@yakov116 4.30 ? what is that?????

**Comment by yakov116** [comment] 2017-09-10 17:05
@k0shk0sh lol a 3 got stuck in there

**Comment by k0shk0sh** [comment] 2017-09-10 17:06
@yakov116 please be more specific, 3 got stuck in there ain't gonna make the comment explain itself.

**Comment by yakov116** [comment] 2017-09-10 17:06
@k0shk0sh Shall I compile a debug ver of 4.0 and have them try it?

**Comment by k0shk0sh** [comment] 2017-09-10 17:08
@yakov116 you are now stating the opposite of what I stated, I SAID that there is nothing changed regards editing issue at all from its first launched :) so doing that ain't gonna make any difference, why would I be able to edit issues in here or in your private repo not even public ones and they can't? 

it doesn't make sense.

**Comment by yakov116** [comment] 2017-09-10 17:09
@k0shk0sh Agree with you! But as we know github many does not make sense 😆

**Comment by zvirja** [comment] 2017-09-10 17:24
Just tested the v4.1.0 - issue is still there. So indeed, that is not a regression.

> With that said, maybe I suggest you guys to contact GitHub 

It would be better that _you_ contact them. You are the one who knows something about API you use and more implementation detail. I could provide the required data for you (probably, except tokens that can be used to perform actions with my credentials).

As I [previously mentioned](https://github.com/k0shk0sh/FastHub/issues/948#issuecomment-328326748), could you please provide me with API call I should perform to close the issue? I could run it with my current credentials and see a reply.

**Comment by k0shk0sh** [comment] 2017-09-10 17:27
Unzip the apk, install it without uninstalling production app, they will be separate so no worries about that. 


try and edit, once it says copied to clipboard, paste it here. 


[app-debug.apk.zip](https://github.com/k0shk0sh/FastHub/files/1290744/app-debug.apk.zip)

**Comment by k0shk0sh** [comment] 2017-09-10 17:31
https://developer.github.com/v3/issues/#edit-an-issue


```
PATCH https://api.github.com/repos/Onwer/RepoName/issues/Number

Body 

{
  "body": "**FastHub Version: 4.2.0**  \n**Android Version: 7.1.2 (SDK: 25)**  \n**Device Information:**  \n- **Manufacturer:** OnePlus  \n- **Brand:** oneplus  \n- **Model:** OnePlus One  \n---\n\nWhen I try to submit an issue edit, it says \"not editable by <me>\"\n\nWorks fine from github web desktop on chrome android.\nThis happened on 4.1.0 as well...",
  "labels": [
    "Type: Can't produce",
    "Type: Duplicate"
  ],
  "state": "closed",//or open
  "title": "Can't edit my own issues from FastHub"
}
```

and of course your credential details. 

I suggest you to use  postman to ease things.

**Comment by k0shk0sh** [comment] 2017-09-10 17:45
@Younes-L  @zvirja  any news from you guys???

**Comment by zvirja** [comment] 2017-09-10 17:46
I've stuck with authentication.. What exactly should I pass to request (e.g. cookie name)?

**Comment by yakov116** [comment] 2017-09-10 17:48
@zvirja can you try the app @k0shk0sh posted?

**Comment by zvirja** [comment] 2017-09-10 17:55
I opened the Postman app in Chrome and am composing the query. I get reply from GitHub that authentication required. Also I cannot set the cookie value.. 🦀

**Comment by yakov116** [comment] 2017-09-10 17:56
@zvirja Use the app....

**Comment by k0shk0sh** [comment] 2017-09-10 17:57
@zvirja no cookie, use basic auth within the post

**Comment by zvirja** [comment] 2017-09-10 18:01
@k0shk0sh It doesn't work due to 2-factor authentication 😩 Will try to obtain a token somewhere..

**Comment by k0shk0sh** [comment] 2017-09-10 18:02
use your name and access token

**Comment by zvirja** [comment] 2017-09-10 18:06
Finally 🎉

Request to `https://api.github.com/repos/k0shk0sh/FastHub/issues/948`:
```json
{
  "state": "open"
}
```
Reply:
```json
{
    "message": "Validation Failed",
    "errors": [],
    "documentation_url": "https://developer.github.com/v3/issues/#edit-an-issue"
}
```

**Comment by k0shk0sh** [comment] 2017-09-10 18:08
so did you use the app so you could help me find out the problem?

**Comment by zvirja** [comment] 2017-09-10 18:23
Just found that issues from this repo are not good candidates as I cannot re-open them via site neither. Therefore, decided to use the original issue.

Issue `https://github.com/prodot/ReCommended-Extension/issues/25`
Query via Postman:
`https://api.github.com/repos/prodot/ReCommended-Extension/issues/25`
```json
{
  "state": "open"
}
```

Successful reply.

If I try to do that via app - says that issue is not editable by me.

**Comment by zvirja** [comment] 2017-09-10 18:30
I have a suspicion that you are setting more properties that I actually have access to, so that's might be the reason.

Also I used the manually generated token in GitHub will all the possible permissions - not sure that your token has the same rights.

**Comment by zvirja** [comment] 2017-09-10 18:34
Just tested again - perfectly fine in API, but doesn't work in app. Let me know which further steps you want me to try 😉

**Comment by wxl** [comment] 2017-09-11 07:16
I'm having the same issue with 4.2.0 and Android 7.0 on a Galaxy S7.

**Comment by k0shk0sh** [comment] 2017-09-11 16:47
so none of you guys actually tested the APK i uploaded, what a waste of time to build a modified version but no response :) .. 

👏 


@wxl I'll contact GitHub and see what they have changed/done to break that

**Comment by k0shk0sh** [comment] 2017-09-11 16:55
I have contacted github with no info at all and awaiting their reply. 
Maybe you guys could provide me such details: 

1- how did you login?. 
2- how many accounts are you logged in with?
3- have you ever tried before editing issue via FastHub and this occur?

**Comment by zvirja** [comment] 2017-09-11 19:28
> what a waste of time to build a modified version but no response 

I've spent more than one hour yesterday trying to send that request via Postman. It doesn't seem that you used my results somehow 😟

> none of you guys actually tested the APK i uploaded

I missed that point. Could you share a link to the app? Could you also confirm that app will not leak my token to you among diag logs? 😕

> Maybe you guys could provide me such details:

Sure.
1. I used login via browser and later provided application with access to my account. FastHub is listed in `Authorized OAuth apps` in my account.
2. Single account.
3. Haven't got the question, sorry. I don't remember whether previously I had this issue. Just tried and it's still reproducible - it's definitely something with app & GitHub interaction as it's persistent.

Hope that helps 😉

**Comment by yakov116** [comment] 2017-09-11 19:31
@zvirja please download this
https://github.com/k0shk0sh/FastHub/files/1290744/app-debug.apk.zip
unzip and try it

**Comment by zvirja** [comment] 2017-09-11 19:40
App crashed in reopen. Is that expected?

**Comment by wxl** [comment] 2017-09-11 19:49
> 1- how did you login?.

Unknown. It's been a long time ago! 

> 2- how many accounts are you logged in with?

One. 

> 3- have you ever tried before editing issue via FastHub and this occur?

I'm pretty sure I've edited before with no issues.

**Comment by k0shk0sh** [comment] 2017-09-11 19:49
No such things will logged, the error will be copied to your clipboard so when you paste here and before hitting that submit button double check :p

**Comment by k0shk0sh** [comment] 2017-09-11 19:50
@wxl  i'm pretty sure its something to do with GitHub :'( I CAN'T FIGURE IT OUT AT ALL.

**Comment by zvirja** [comment] 2017-09-11 19:53
@k0shk0sh The debug application simply crashed and nothing was copied to the clipboard.. Am I doing something wrong?

**Comment by k0shk0sh** [comment] 2017-09-11 19:55
then my impl crashed if you reached to the edit screen & u made the API call and then the app is crashed :D . will try and find better way :D . tomorrow tho. nighty night for me

**Comment by zvirja** [comment] 2017-09-11 19:57
Yesterday I tried to perform the API call directly and everything was fine. Could you check that you update status only and no other fields are present in the reopen API call?

**Comment by wxl** [comment] 2017-09-11 20:01
Debug app crashed with nothing on clipboard.

**Comment by yakov116** [comment] 2017-09-11 20:03
@zvirja and @wxl, Thanks for all your help! @k0shk0sh has hit the pillow for the night. He will try tomorrow again.

Thanks for your help!

**Comment by Younes-L** [comment] 2017-09-11 23:39
@k0shk0sh 

1- logged in with username-password on the fasthub app, and granted access to my account for fasthub at some point (maybe that happens when I first login ?)

2- only 1 account, this one

3- yes I edited issues with no problems before, first time I encountered this problem (4.1.0)


Sorry for not checking here recently, I thought this issue was definitely closed 😅

**Comment by k0shk0sh** [comment] 2017-09-12 12:11
> About the specific problem you're reporting now -- I'm not aware of any changes made on our end, but I was able to reproduce the strange behavior your users reported. The problem happens when users try to edit issues in a public organization-owned repository which have this feature enabled and your application was no whitelisted by those organizations:

https://help.github.com/articles/about-third-party-application-restrictions/

As far as I know, that feature shouldn't be interrupting such operations on public repositories, so this seems like a problem on our end. I'll open an internal issue so that the team can investigate. I can't promise an ETA, but we'll followup as soon as there's any news.


that's GitHub reply :)

**Closed** 2017-09-12 12:12 UTC
Labels: Type: Can't produce

**Comment by zvirja** [comment] 2017-09-12 12:16
Just checked the issue I used for the reproduction above - it indeed belongs to an organization.

Thanks for firing the issue and your efforts 😉

**Comment by Younes-L** [comment] 2017-09-12 21:39
great news !!

**Comment by k0shk0sh** [comment] 2017-09-14 06:35
> 
The team deployed some changes which should have fixed the problem you reported (issues not being editable). If you can still reproduce this — please let us know and provide the information I mentioned in my previous reply.


please do check again

**Comment by zvirja** [comment] 2017-09-14 06:38
Thank you @k0shk0sh. I've just checked and can confirm that now everything works fine! :blush::+1::star2:

**Comment by wxl** [comment] 2017-09-14 16:05
Also confirmed. Thanks @k0shk0sh. It may not have been your fault but you fixed it!

**Comment by Younes-L** [comment] 2017-09-14 18:21
submitting edit - success !!

awesome work 👍
