### ISSUE TITLE
Add a button to subscribe/unsubscribe

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#974] opened 2017-09-15 06:40 UTC
**FastHub Version: 4.2.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi 5  
---

Add a feature to subscribe/unsubscribe from issue/PR notifications. This is really minor feature, as I need this rarely and could open issue in the browser for this purpose. :wink:

**Comment by zvirja** [comment] 2017-09-15 06:42
Okay :worried:

**Comment by k0shk0sh** [comment] 2017-09-15 06:46
it's not that I don't want to implement, there is no api for it

**Comment by zvirja** [comment] 2017-09-15 06:51
Isn't [this API](https://developer.github.com/v3/activity/notifications/#set-a-thread-subscription) exactly about this feature? I could miss something, but at the first glance it looks like the right API.. :sweat:

**Comment by k0shk0sh** [comment] 2017-09-15 07:15
where is the thread ID, that's the problem lol

**Comment by zvirja** [comment] 2017-09-15 08:51
Briefly Googled and indeed it seems to be the issue :unamused:

**Comment by dedepete** [comment] 2017-09-18 13:21
I don't think this research can help you, but I have just found `thread_id` in the page's source code.  
![image](https://user-images.githubusercontent.com/1936922/30543834-24f30b60-9c8d-11e7-8792-49527a526ac4.png)

**Comment by yakov116** [comment] 2017-09-18 13:54
@dedepete but it is not in the api response

**Comment by dedepete** [comment] 2017-09-18 13:57
@yakov116 there should be a way to get it via api.

**Comment by yakov116** [comment] 2017-09-18 14:04
@dedepete should be... that is a word github does not have in their language book :stuck_out_tongue:

We have learnt the hard way that if they don't have it don't expect it anytime soon.

**Comment by Phoenix09** [comment] 2017-10-12 20:38
but the API does provide it.

https://api.github.com/repos/k0shk0sh/FastHub/issues/974
notice the id value?

which funnily enough, matches the thread_id input for the from on the site.

so clearly it's a case of "don't want to"

**Comment by k0shk0sh** [comment] 2017-10-13 05:35
they added it lately then . thanks

**Comment by zvirja** [comment] 2017-10-13 09:37
Should we re-open this one?

**Comment by k0shk0sh** [comment] 2017-10-13 17:31
the good new is, implementing this won't take even 10 minutes because I already have the code for that, a matter of changing API call :)

**Comment by k0shk0sh** [comment] 2017-10-14 07:45
well well, 
`D: <-- 403 Forbidden https://api.github.com/notifications/threads/264319772/subscription`
`{"message":"Must have admin rights to Repository.","documentation_url":"https://developer.github.com/v3/activity/notifications/#set-a-thread-subscription"}`

I hate github API!!!!

**Comment by jancborchardt** [comment] 2017-11-10 18:40
It's not really a solution, but in Octodroid when you go back from an issue to the Notifications list, that issue is shown greyed out. From the notifications you can seemingly unsubscribe (whereas from inside the issue you can not).

**Comment by k0shk0sh** [comment] 2017-11-10 18:42
@jancborchardt I didn't get your point in here, but from the notification list, the notificationId is provided, however in the issue isn't. 

This wont be fixed until Github decide to change their API which four months ago they said that they will work on.

**Closed by k0shk0sh** 2017-11-10 18:42 UTC
Labels: Priority: Critical, Status: Accepted, Status: In Progress, Type: Feature Request
