### ISSUE TITLE
Trending repos Not working

### ISSUE THREAD

**Issue by ygunduz** [k0shk0sh/FastHub#2510] opened 2019-06-13 20:28 UTC
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Redmi Note 5  
---

 There is an error while fetching trending repositories.  It says 'No Trending'

**Comment by yakov116** [comment] 2019-06-13 20:30
@ygunduz 	
Duplicate of #2508

**Comment by flamendless** [comment] 2019-06-14 02:33
Can confirm this

**Comment by circa10a** [comment] 2019-06-15 22:23
Having same isshe

**Comment by eaglexiang** [comment] 2019-06-16 07:22
the same issue

**Comment by qingspring** [comment] 2019-06-18 08:22
have the same issue

**Comment by mafeifan** [comment] 2019-06-27 14:55
same issue, i am premium user.  plz fix asap.  thx

**Comment by mafeifan** [comment] 2019-06-28 00:47
seems the structure  of github trending page changed, so fasthub parse html failed.. i think it's not hard to fix.

**Comment by muellercornelius** [comment] 2019-07-11 21:05
Same problem here ;(

**Comment by BaldEagleX02** [comment] 2019-07-20 14:16
Same issue here

**Comment by k0shk0sh** [comment] 2019-07-20 16:10
It isn't hard to fix, its fixed in v5 but its not possible anymore in old FastHub 🤷‍♂️

**Comment by eaglexiang** [comment] 2019-07-20 18:14
@k0shk0sh Could you push the update to google play store?

**Comment by k0shk0sh** [comment] 2019-07-20 18:55
V5 isn't ready for prod yet but im working on that! Please be patient :)

**Comment by glebcha** [comment] 2019-07-29 19:38
@k0shk0sh when it will be finished?

**Comment by k0shk0sh** [comment] 2019-07-29 19:53
No exact timeline, end of October max!

**Comment by ilazaroy** [comment] 2019-08-23 16:03
@k0shk0sh thanks for the help.

**Comment by zeromake** [comment] 2019-08-25 13:15
You can use [my-fix](https://github.com/zeromake/FastHub/releases/tag/4.6.7-debug)

**Comment by ilazaroy** [comment] 2019-08-25 13:26
Yep, did the trick.
Thanks man and thank you for the great app! Super easy to explore trending
repos this way.

**Comment by glebcha** [comment] 2019-12-04 21:36
When it'll be fixed? Just write damn date.

**Comment by yakov116** [comment] 2019-12-04 21:48
>Just write damn date.
date 😄

**Comment by glebcha** [comment] 2019-12-07 18:37
@yakov116 whatever, think about "date" in context of time

**Closed** 2019-12-25 11:52 UTC
Labels: Known Issue, Status: Completed
