### ISSUE TITLE
Trending is not showing anything anymore

### ISSUE THREAD

**Issue by sonamghosh** [k0shk0sh/FastHub#2511] opened 2019-06-13 22:06 UTC
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note9  
---
The app started displaying nothing on the trending app as of a few days ago and is an ongoing problem

**Comment by yakov116** [comment] 2019-06-13 22:54
Duplicate of #2510

**Closed by yakov116** 2019-06-13 22:54 UTC
