### ISSUE TITLE
Jump to comment: comment is added at wrong position 

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#1181] opened 2017-10-24 18:36 UTC
**FastHub Version: 4.5.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Tab S2 8.0  
---

Open the following link: https://github.com/AutoFixture/AutoFixture/issues/703#issuecomment-339087757

Instead of scrolling to the comment at the very bottom, the comment is inserted as the first reply. Something weird happens to this comment :confused:

**Comment by zvirja** [comment] 2017-10-25 09:43
It seems you misunderstood the issue. That **is not** the expected behavior.

The comment this link points to is _the last_ comment in the thread (for now). If you open in the browser you'll find it at the very bottom of the page. However, if you open this link in the app, it will insert that comment as the _first comment_.

The application inserts comment to the wrong position and makes it the first one. It's definitely a bug. Please test and see the difference.

Let me know if you cannot reproduce it and need some screenshots. I observed this behavior on 2 devices, so the scenario is stable.

**Comment by k0shk0sh** [comment] 2017-10-25 09:48
I understood your issue and marked it as a word as intended which mean I made it to work that way at least for now ;). 

Don't always assume that I miss understood your argument despite sometimes I do :p. 

With that said, I have no interest to waste more time on working on this until I feel like I have to time to waste.

**Comment by zvirja** [comment] 2017-10-25 09:55
Well, often you close issues without any explanation. There is no chance to understand what you meant 😕

It's a very strange behavior as it changes how the comments are understood. You simply cannot trust the app output more if it could reorder the comments.

This issue happens each time I open the issue using the link in email notification. I believe that clients of your app will observe it often as well. It's very confusing and unclear behavior and it totally violates the [principle of the least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). If you have some technical limitations, it would be better to do nothing at all - simply open the thread and do not jump.

**Comment by k0shk0sh** [comment] 2017-10-25 09:58
well, I think fuck it, I will load 1000 comments just to scroll to 999. which that equals to more than 100 API REQUEST.  

P.S: DO NOT LATER OPEN AN ISSUE STATING LOADING COMMENTS IS SLOW

**Comment by k0shk0sh** [comment] 2017-10-25 09:58
#440

**Comment by zvirja** [comment] 2017-10-25 10:11
>  I will load 1000 comments just to scroll to 999

I don't ask you about such a behavior. Feel free to simply stop loading them with e.g. a toast notification "Sorry, cannot jump - too many issues". That would be much better behavior that putting comment at the beginning. My issue was about the confusion the current behavior causes - not about the technical limitations you have.

**Comment by k0shk0sh** [comment] 2017-10-27 18:53
if the comment isn't in the first page, a message will appear.

**Comment by zvirja** [comment] 2017-10-27 19:01
@k0shk0sh Cool, thanks :blush:

BTW, would it be possible to add a setting for that behavior? To toggle between message and preload of 1000 messages if needed? That will ensure that app behavior will satisfy everybody.

What would you say?

**Closed** 2017-10-28 18:02 UTC
Labels: Priority: Critical, Status: Accepted, Status: Completed, Type: Enhancement
