### ISSUE TITLE
Abuse detection mechanism triggered for searches

### ISSUE THREAD

**Issue by ishitatsuyuki** [k0shk0sh/FastHub#1619] opened 2018-03-14 15:05 UTC
**FastHub Version: 4.6.4**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** P10 Plus  
---

After performing a combination of repository, path and code (files) search, it will trigger the abuse detection and the IP-token combination is banned from searching files for a while.

The amount of searches before getting banned (5 on average) is significantly less than what is documented as search rate limit (30 req/min).

```
You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.
```

The possible causes are documented at [here](https://developer.github.com/v3/#abuse-rate-limits). The reasons I can think of are:
- FastHub may be repeatedly performing requests in background, like the status API.
- FastHub may be retrieving the pagination too rapidly.

**Comment by k0shk0sh** [comment] 2018-03-14 15:06
Search API has its own limit and is not tied to the other apis.

**Comment by ishitatsuyuki** [comment] 2018-03-14 15:07
Yes it is and as I mentioned it's 30/min compared to the normal 5000/min. We're not triggering a documented rate limit but their private abuse detection mechanism.

**Comment by k0shk0sh** [comment] 2018-03-14 15:09
Well, I can't tell what's the problem here honestly,  I never encountered such behavior. 

Maybe you do alot of pagination in the search? This could be the cause as well. I can't help you tho as idk what is going.

**Comment by ishitatsuyuki** [comment] 2018-03-14 15:12
Please follow the following reproduction steps:

1. Search repo for FastHub
2. Open this repo
3. Search the code with generic keyword (e.g. get, API, kotlin) for 10 times

I got banned this time very quickly.

**Comment by k0shk0sh** [comment] 2018-03-14 15:20
10 times straight?? or there is some seconds in between?

**Comment by ishitatsuyuki** [comment] 2018-03-14 15:22
You probably should do the search as fast as you can type, as it's likely still below the rate limit.

By the way, if you can't reproduce, I would file a case with GitHub support and post back with what they says.

**Comment by k0shk0sh** [comment] 2018-03-14 15:26
I could produce it but after many requests and selecting All from the spinner. which is legit in my opinion. its up to you if you like to fire a case to GitHub :)

**Comment by ishitatsuyuki** [comment] 2018-03-15 03:01
All GitHub suggested is to respect the Retry-After header:

> In general, the best thing to do is to spread your requests over time and check the Retry-After header in case you do hit the secondary limits, so that you know when you can resume making requests.

We should show "retry after x seconds" when the header is present, and optionally fail all requests internally instead of requesting GitHub server (so the count doesn't get worse).

**Comment by yakov116** [comment] 2018-03-15 03:33
@ishitatsuyuki rather don't try make the server fail and you won't have any issues at all

**Comment by ishitatsuyuki** [comment] 2018-03-15 03:35
@yakov116 FastHub can perform multiple requests or implicitly request the server, such as fetching status.

**Comment by yakov116** [comment] 2018-03-15 03:39
@ishitatsuyuki but as you understand this is a non standard thing. You are more than welcome to submit a pr

**Comment by yakov116** [comment] 2018-03-15 03:39
@ishitatsuyuki but as you understand this is a non standard thing. You are more than welcome to submit a pr

**Comment by ishitatsuyuki** [comment] 2018-03-15 03:40
What? Non-standard? Please elaborate.

**Comment by yakov116** [comment] 2018-03-15 03:53
@ishitatsuyuki this is issue number #1619 you are the first person I know that has run into this issue

**Comment by ishitatsuyuki** [comment] 2018-03-25 08:40
I believe the root cause of this is because in the "search everything" interface we load the four types of search result concurrently. Can you reopen this issue?

**Comment by k0shk0sh** [comment] 2018-03-25 13:09
I doubt that this is the cause :) for instance, issues and pr tabs in main screen are also search and in some other places as well where there is no API i use search api.

**Comment by ishitatsuyuki** [comment] 2018-03-25 13:14
To elaborate, I have some more points of that being a cause:

- The abuse rate limit is triggered in the "search everything" panel the first time in most of my cases. The rest of triggered in repository code search.
- The 4x amplification makes sense when it comes to hitting 30req/min rate limit.
- [GitHub recommends against concurrent requests](https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits).
  > Make requests for a single user or client ID serially. Do not make requests for a single user or client ID concurrently.

**Comment by yakov116** [comment] 2018-03-25 13:37
@ishitatsuyuki its interesting since you are the only one reporting this. I am using FastHub for a year now and I have never encountered this issue!

**Comment by ishitatsuyuki** [comment] 2018-03-25 13:39
@yakov116 Please stop repeating the fact that this is "interesting". It does not contribute to discussion. The only thing I can say is that, **it affects me**.

**Comment by delugeduser** [comment] 2018-06-19 08:56
Yep very interesting. Very interesting. Yes interesting.  In other words we aint doing jack-shit about it. These guys must also run systemd given their dismissive approach. It sure is a problem that gets triggered after 3 pages of search. Laughable. Perhaps you need to disable search given it seems your i486 is hard pressed to service 3 pages in 30 seconds.

**Comment by hpg-mheck** [comment] 2019-02-13 08:32
I can trigger this issue with a single, manual search for "fabric-composer" on the first try with no special crap.  This is a vanilla, manual search from Chrome on Linux.  This is a real pain in the ass.

**Comment by k0shk0sh** [comment] 2019-02-13 08:40
Guys, this has been fixed in v5 as im using graphql for that, so please be patient.

**Comment by k0shk0sh** [comment] 2019-02-13 08:43
![screenshot_20190213-094326](https://user-images.githubusercontent.com/960767/52698498-dd2d7880-2f73-11e9-8640-647ce952d92d.png)

**Closed** 2019-02-13 08:44 UTC
Labels: Type: Work as Intended

**Comment by Kaju-Bubanja** [comment] 2019-11-11 07:43
Why is this closed? This is still an issue. Trying to search something for the first time already triggered this for me.

**Comment by alogim** [comment] 2019-11-12 20:29
I am experiencing the same issue, and I am doing one search every 2 or 3 seconds...

**Comment by bo3b** [comment] 2019-11-15 02:38
Just did **ONE** search on a clean install of Win10 1903, using Chrome browser, and it triggered.  

No idea why this would be closed.  I had to login to be able to do anything.
