### ISSUE TITLE
Loading dialogs are dismissable

### ISSUE THREAD

**Issue by wasdennnoch** [k0shk0sh/FastHub#560] opened 2017-05-28 09:37 UTC
**App Version: 2.5.1**

**OS Version: 25**

**Model: samsung-GT-I9305**

 When clicking outside a loading dialog with the circular progressbar it dismisses it, leaving you with a blank page and the request loading in the background.

I'd suggest either making it undismissable but then the user couldn't go back while it's loading; a more elegant solution is to extract the loading bar into the started activity itself so instead of just a blank page with a blank header and dialog on top you see a progressbar with a blank header. I hope that's understandable.

**Comment by yakov116** [comment] 2017-05-28 13:54
@k0shk0sh Is this a duplicate of #471?

**Comment by wasdennnoch** [comment] 2017-05-28 14:02
Not entirely; this issue seems to more refer to the readme loading. It may be on purpose but I say it's a bad design choise :P

**Comment by JediBurrell** [comment] 2017-05-28 14:40
@wasdennnoch the README page has a progressbar even if you dismiss the dialog.

**Comment by wasdennnoch** [comment] 2017-05-28 14:58
Only after the repository info itself loaded. And issues don't have any other loading indicator.

**Closed** 2017-09-17 12:57 UTC
Labels: Priority: Low, Status: Completed, Type: Enhancement
