### ISSUE TITLE
Deleted branch names are not resolved

### ISSUE THREAD

**Issue by sschuberth** [k0shk0sh/FastHub#884] opened 2017-08-24 12:11 UTC
**FastHub Version:**  4.0.3
**Android Version:**  6.0.1
**Device Information:**  Samsung S6

If a source branch was deleted after merging a PR, FastHub displays just `head ref deleted` in the events. It would be nice if `head` was resolved to the actual branch name.

**Comment by k0shk0sh** [comment] 2017-08-24 12:13
yep, I found this today and didn't get around it. I'll see about it.

**Comment by k0shk0sh** [comment] 2017-08-24 12:17
wanted to ask, are you using production or debug apk?

**Comment by sschuberth** [comment] 2017-08-24 12:19
Production, straight from the store.

**Comment by yakov116** [comment] 2017-08-24 13:49
@k0shk0sh I don;'t think there is a simple way to do this without GraphQl. Don't think its worth putting in time when it will be fixed with that.

**Comment by sschuberth** [comment] 2017-08-25 08:42
Doesn't it make sense to keep this open as a reminder until this *is* implemented, regardless of *how* it's being implemented (GraphQL or not)?

**Comment by k0shk0sh** [comment] 2017-08-25 08:43
Its fixed? isn't the problem is that when you open a PR that has the branch
deleted you get an error? if that's the case then its fixed

*Thanks.*
*Best Regards,*
*Kosh*



<https://about.me/imkosh?promo=email_sig>

**Comment by sschuberth** [comment] 2017-08-25 08:56
No, I was not getting an error. It's purely a display issue. See this screenshot to clarify:

![fasthub](https://user-images.githubusercontent.com/349154/29706992-fad15f42-8983-11e7-8d3e-be67ef79a588.png)

Like in the [web interface](https://github.com/heremaps/gradle-jenkins-jobdsl-plugin/pull/44), the branch name "readme-2.0.0" should be displayed instead of just "head".

**Comment by k0shk0sh** [comment] 2017-08-25 09:09
owh dang, I thought its something really different lol

**Comment by k0shk0sh** [comment] 2017-08-25 09:11
looking at this response: 

```
{
        "id": 1220388559,
        "url": "https://api.github.com/repos/k0shk0sh/FastHub/issues/events/1220388559",
        "actor": {
            "login": "yakov116",
            "id": 16872793,
            "avatar_url": "https://avatars2.githubusercontent.com/u/16872793?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/yakov116",
            "html_url": "https://github.com/yakov116",
            "followers_url": "https://api.github.com/users/yakov116/followers",
            "following_url": "https://api.github.com/users/yakov116/following{/other_user}",
            "gists_url": "https://api.github.com/users/yakov116/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/yakov116/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yakov116/subscriptions",
            "organizations_url": "https://api.github.com/users/yakov116/orgs",
            "repos_url": "https://api.github.com/users/yakov116/repos",
            "events_url": "https://api.github.com/users/yakov116/events{/privacy}",
            "received_events_url": "https://api.github.com/users/yakov116/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "head_ref_deleted",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2017-08-24T19:51:43Z"
    }
```

I don't think its possible, anyway you could actually figure out the name by looking under the title in the header which will tell you the branch name.

**Closed by k0shk0sh** 2017-08-25 09:11 UTC
Labels: Status: Won't Fix

**Comment by sschuberth** [comment] 2017-08-25 09:22
Well, with GraphQL it *is* possible: https://developer.github.com/v4/reference/object/headrefdeletedevent/

Also, as the branch name does not change during a PR, couldn't you just re-display the branch name from the title header instead of displaying the even name?

**Comment by k0shk0sh** [comment] 2017-08-25 09:24
Well, I have spent a month with Graphql for PR timeline & it delayed the update of FastHub until today & just two days ago I have reverted back to use v3 but with different API. so until GitHub fix their freaking API I'm going to stay away from Graphql at least for PR timeline.

**Comment by mueller-ma** [comment] 2018-03-07 07:49
Doesn't is make more sense to change it from "John Doe `head ref deleted`" to "John Doe deleted head ref"?

**Comment by MuhammadFaridHamid90** [comment] 2018-03-07 17:01
John 
## Doe
### head**ref_deleted_ **

**Comment by yakov116** [comment] 2018-03-07 17:06
@sschuberth @mueller-ma the reason its like this is because we attempted to switch to graphql which gives us the branch. However we did not switch but the wording setup stayed the same.
