### ISSUE TITLE
Commit info flash

### ISSUE THREAD

**Issue by Otto-G** [k0shk0sh/FastHub#2378] opened 2019-04-08 11:20 UTC
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 3  
---

 When looking at a commit detail page, pressing the info i button will bring up a page that flashes between being top and bottom aligned

**Comment by yakov116** [comment] 2019-04-08 12:32
Duplicate of #2281

**Closed by yakov116** 2019-04-08 12:32 UTC
