### ISSUE TITLE
Feature Request Add search option 

### ISSUE THREAD

**Issue by ryanmusante** [k0shk0sh/FastHub#1722] opened 2018-04-11 06:15 UTC
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** docomo  
- **Model:** Xperia XZ  
---

![Drop down ](https://i.imgur.com/0zG7ZES.jpg)

Request to add search option to drop down menu for viewing files on github file view screen.

**Comment by PacoBell** [comment] 2018-06-10 04:12
Isn't this FR pretty much a duplicate of https://github.com/k0shk0sh/FastHub/issues/967 ?

**Comment by yakov116** [comment] 2018-06-17 16:05
@PacoBell Yes it is 

Marking As Duplicate of #967

**Closed by yakov116** 2018-06-17 16:05 UTC
