### ISSUE TITLE
Trending repos aren't loading

### ISSUE THREAD

**Issue by RuthwikHM** [k0shk0sh/FastHub#2513] opened 2019-06-14 08:31 UTC
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G (5S) Plus  
---

 The trending tab on my device has stopped showing anything. It says no data found. Might be a client side error in your app. Please solve it ASAP

**Comment by Baldomo** [comment] 2019-06-14 10:41
Duplicate of #2508

**Closed** 2019-06-14 15:26 UTC
