### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by OffifialMITX** [k0shk0sh/FastHub#455] opened 2017-05-10 08:08 UTC
(Or am I just doing something wrong?)

Account name and E-Mail Account don't work, I just get a very long Error message (SS in ~12h)

Btw, GitHub already shows me FastHub as an authorized application but the app itselg refuses for some reason.

 - FastHub Version: 2.0.1 F-Droid
 - Android Version: 5.1.1
 - Phone Model: Neffos C5L

**Comment by k0shk0sh** [comment] 2017-05-10 08:11
Could you tell me what are steps you done? Are you trying to login from local? Or from playstore or fdroid? 
Also are you trying to login via access token, basic auth or via browser?

**Comment by OffifialMITX** [comment] 2017-05-10 09:58
Yeah, sorry,
How am I supposed to login from F-Droid? I got it from there of that's what you mean and I've tried the basic login. If using the browser, is the chrome browser really the only possible one?

**Comment by k0shk0sh** [comment] 2017-05-10 10:00
Hmmm strange. 
@thermatk any input on this or what could be the cause here?

Chrome by far the safest way to login via browser as most browsers don't support deep linking in Android, therefore you might be stuck in just an empty screen in the browser.

**Comment by k0shk0sh** [comment] 2017-05-10 14:19
_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by thermatk** [comment] 2017-05-10 15:49
Tried basic and browser with Firefox, both work well
The trick with Firefox is to press the little Android in the address bar which always appears there in case there is an intent associated with url

**Comment by ildar** [comment] 2017-05-10 21:47
Seen that.
Basic.
Mistyped the password. Then the right password took me to the "Exception inserting a record" with many question marks.

**Comment by k0shk0sh** [comment] 2017-05-11 00:07
@thermatk  I'm no longer allowing any other browser but chrome. How can you use Firefox :p 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment] 2017-05-11 00:33
@ildar Oops, you mean like it login correctly but then the app crash? Or how?

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ildar** [comment] 2017-05-11 01:56
Well, it didn't crash. Just showing a big modal dialog for a few seconds
then allowing you to try again.
If you still cannot reproduce, I'll try it later today with PC at hand to
get adb logcat

**Comment by ildar** [comment] 2017-05-11 05:12
Truly easily reproducible:
1. Launch app for the 1st time
2. Choose Basic auth
3. Enter login+password, tap the button to login
4. The popup "Join slack" appears. Tap somewhere over it (e.g. on the login
field)
5. The popup disappeared but login didn't happen. Now you cannot login
anymore

**Comment by k0shk0sh** [comment] 2017-05-11 05:16
@ildar In this case this wont happen again. Since the dialog wont appear until you actually go to main activity

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ildar** [comment] 2017-05-11 05:36
You didn't try it yourself. A user cannot login anymore after that.
Exception happens.
BTW unfortunately the Exception is invisible in logcat.

**Comment by k0shk0sh** [comment] 2017-05-11 05:37
@ildar I did, and nobody reported such issue but you and the OP, so yeah. 
> I wont release something that is not tested. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ildar** [comment] 2017-05-11 05:42
Didn't quite understand. Do you see the red toast with text "Exception
blah-blah"?

**Comment by k0shk0sh** [comment] 2017-05-11 05:44
@ildar nope! 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by thermatk** [comment] 2017-05-11 05:48
@k0shk0sh I somehow get the intercepted intent and choose Firefox, might be because I have chromium installed, but not default. So, unblock other browsers! Firefox works for sure

**Comment by ildar** [comment] 2017-05-11 05:56
I see. That must be the 2.0.1 issue that isn't in 2.1.
2.1 isn't available yet on F-Droid. We'll see.

**Comment by k0shk0sh** [comment] 2017-05-11 06:03
@ildar owwwh shit, no wonder. I was wondering too and cracking my head up. That explains it all tho. 2.2.0 will be out Sunday. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment] 2017-05-11 06:04
@thermatk Firefox trick only you might know it not everyone. As described in one of the issues that I closed awhile ago about Organization not being listed . 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by thermatk** [comment] 2017-05-11 06:24
https://f-droid.org/wiki/page/com.fastaccess.github#2.1.0 got autoupdated and built as planned, will be in store next signing session
@k0shk0sh as long as basic works I can't care less, but locking out people without Chrome/Chromium is not a solution. The majority of browsers can handle links properly. 
A true fix would be not to redirect to some non-existent https, but to redirect to a protocol, this way you get 99% interception. Like "fasthub://login"

**Comment by k0shk0sh** [comment] 2017-05-11 06:26
@thermatk yup that is correct, it just that its too late for that to change as I'm afraid of the impact that will happen to anyone that downloads an older version. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by thermatk** [comment] 2017-05-11 06:40
you can intercept both links?

**Comment by k0shk0sh** [comment] 2017-05-11 06:41
the app can, but Github won't. only one url can be a callback in github

**Comment by thermatk** [comment] 2017-05-11 07:12
then, new separate keys for new logins? :rofl: the GithubConfigHelper.java abstraction is already there, can work with more complex things :+1:

**Comment by JediBurrell** [comment] 2017-05-13 01:22
@k0shk0sh Can you not do a PHP script as the callback to compare versions and give an appropriate URI?

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by OffifialMITX** [comment] 2017-05-14 10:07
Now it's working out of nowhere.

**Comment by k0shk0sh** [comment] 2017-05-14 10:11
@OffifialMITX have you updated to 2.1.0? This might be the reason :p

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by OffifialMITX** [comment] 2017-05-14 10:14
Not yet, but I've opened it once without an internet connection, somehow it seems to solve the problem.

**Comment by k0shk0sh** [comment] 2017-05-25 01:27
This has been fixed in https://github.com/k0shk0sh/FastHub/commit/47d9a4810b8154feb7ef742ef903f109fcd80d3a

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Closed** 2017-05-25 01:27 UTC
Labels: Status: Completed
