### ISSUE TITLE
Cannot render Jupyter notebook

### ISSUE THREAD

**Issue by secsilm** [k0shk0sh/FastHub#1602] opened 2018-03-09 04:40 UTC
**FastHub Version: 4.6.4**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** MI6  
---

Cannot render Jupyter notebook.

![](https://i.imgur.com/8MJEEmK.jpg) 

It should be something like the following.

![](https://i.imgur.com/tU4yccz.png)

**Comment by dedepete** [comment] 2018-03-09 04:52
Duplicate of #1069.

_Отправлено с моего P2 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Closed** 2018-03-09 20:59 UTC
Labels: Status: Won't Implement, Type: Duplicate
